# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "dfb04da733bb07161ef4a275c9937370404e96b3fbc63ac9fb4120b1c531b343"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "26682f86a691bb594f2340ca83457791945f8058974c3e9e7b235a5d6335136b"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7d68e45b41a7ff1911e53a5f915da4305191fee9fa2219aa359b3941d0508ce5"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6cc6ce83893d7e573f36936a6582ee96d6984b8608cdc5e3ebb00093f797980a"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Linux_x86_64.tar.gz"
    end
  end

  name "dibs"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/candy-tools/dibs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "dibs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibs"]
    end
  end

  # No zap stanza required
end
