# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "43e567c89dd21264965a22e0ef09cf40c24f749c7dea63947e67cdc566d9c1b4"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "48ea7a342952ce77800a37f684ad799a72f542f9c8284971d788aea27625dc5c"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a7acd30c8c03dd78f337368b6777cd1e5322e05decf10dd50a9a7cd22fcaa54e"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f17ff7e4d8332ad132924d8cad7ba4a532363566ee82371f0e6091b665f6d22d"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Linux_x86_64.tar.gz"
    end
  end

  name "dibs"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/candy-tools/dibs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "dibs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibs"]
    end
  end

  # No zap stanza required
end
