# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "3c5ab91a79a0f2de291df70fcba4dfeb1aad9652c519db103e884b8fa86eabfa"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c5fe9b8eac960209bcada1b8c420af91cecad786833ddf7701507f2d9cb6075f"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1bd5c451b00eae30925ebe64a9beb96ee8007a6e88185c67fd4064de8c0fbff1"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "33bc60ce26b9508d3b3b4e0e3d8ddaec0c4c1ea12519074f867d32b30c6672c4"
      url "https://github.com/candy-tools/dibs/releases/download/v#{version}/dibs_Linux_x86_64.tar.gz"
    end
  end

  name "dibs"
  desc "CLI to check out/in work directories over network drives via rsync"
  homepage "https://github.com/candy-tools/dibs"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "rsync",
    ]

  binary "dibs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dibs"]
    end
  end

  # No zap stanza required
end
