# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-deps-view" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "32136c561c9ea3e5d1211aef0d9e86f82bec6f2dd22720136ecc723ee36157a2"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa4a91f0a330e5129adb9263f4737a62c820328ab6941c8204616d9f82550a48"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "78dc614ed15a65221825095200648dc790f60e91d91baf34338ae2db45ae999a"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "122bf1a0ec428e6aedb6cd6c9eb6b2d475840d135c92db6576dafe76b402b019"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Linux_x86_64.tar.gz"
    end
  end

  name "go-deps-view"
  desc "Browser viewer for a Go module's package dependency graph"
  homepage "https://github.com/candy-tools/go-deps-view"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-deps-view"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-deps-view"]
    end
  end

  # No zap stanza required
end
