# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-deps-view" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "701ffadea51f23d88b9610149babb2c313ec7ea7eb29628b24dedb701d049591"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a659fc5297a567023dd6591d65fb03f3ad452b324d7dd7dbb1aab76fb098202"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bacf2f44364fd7ffd786bbb2b432d2f01751562a896e8b6aa3c636b5cfaf92a2"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7e17f1d48972329ba2c5d5c7689510b55085809e5a1c65f2756a4a9c0caf33f"
      url "https://github.com/candy-tools/go-deps-view/releases/download/v#{version}/go-deps-view_Linux_x86_64.tar.gz"
    end
  end

  name "go-deps-view"
  desc "Browser viewer for a Go module's package dependency graph"
  homepage "https://github.com/candy-tools/go-deps-view"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-deps-view"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-deps-view"]
    end
  end

  # No zap stanza required
end
