# This file was generated by GoReleaser. DO NOT EDIT.
cask "govi" do
  app "govi.app"

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "7b6b3d82a73b497778bc8c90377e286c65939d0af6bc1342470e4a638b2ed412"
      url "https://github.com/candy-tools/govi/releases/download/v#{version}/govi_Darwin_arm64.tar.gz"
    end
  end

  name "govi"
  desc "Minimalistic video player based on mpv"
  homepage "https://github.com/candy-tools/govi"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "#{appdir}/govi.app/Contents/MacOS/govi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govi.app"]
    end
  end

  # No zap stanza required
end
