# This file was generated by GoReleaser. DO NOT EDIT.
cask "todo" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "11c6edbbcc76a932b656719662a3db6421754d33b5cc8eea90e5a82d07ed445b"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f44d9df804efb7a6c5f8cfd52fe2c8b1abf9ee89a9191efa82c709e9a7bcd579"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d25f66a6ff6765147398d266ca414a9cb66191bad23d42a413e5b16d0e32c0a5"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c583254ba72017163033815394d10f80ee2e903171387af20e4e311078e50193"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_x86_64.tar.gz"
    end
  end

  name "todo"
  desc "Keyboard-driven terminal TODO manager backed by plain Markdown files"
  homepage "https://github.com/candy-tools/todo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todo"]
    end
  end

  # No zap stanza required
end
