# This file was generated by GoReleaser. DO NOT EDIT.
cask "todo" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "52cbd7d60199ea637aa9d3e4fbdf0509f2a52c9cc340b8bf97cdeb7659c09428"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "808646b3b002c5bad9327f81cb7d502899ac638fd955cd85ce18738e0f00c56f"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "796a41cef28faaa4ad3d5bc72a75f76825f247c39d8fed36d30ba9af7e290a3d"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f55647e2c2e41b0c6c59895932650f082d28dcc81fb3f042c9daa07dab3f95ad"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_x86_64.tar.gz"
    end
  end

  name "todo"
  desc "Keyboard-driven terminal TODO manager backed by plain Markdown files"
  homepage "https://github.com/candy-tools/todo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todo"]
    end
  end

  # No zap stanza required
end
