# This file was generated by GoReleaser. DO NOT EDIT.
cask "todo" do
  version "0.7.1-b2"

  on_macos do
    on_arm do
      sha256 "a6f2d784eeb5e53c8fe4a69c044f3a16a79368b9dd1aa045bcbd9b0a7aad5022"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7842320de26290cb3766c4b58727891e95ba3c9cc971d8d0dcbdeed3eb8358ff"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1705f535b3f12af3402e8e4240ed6c514cdc0b969b9a65291829407942c099ab"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "953b8b6873a6482ad7bab74e0531564e4c6fe29e7da51d2b1863ff82300ee6b4"
      url "https://github.com/candy-tools/todo/releases/download/v#{version}/todo_Linux_x86_64.tar.gz"
    end
  end

  name "todo"
  desc "Keyboard-driven terminal TODO manager backed by plain Markdown files"
  homepage "https://github.com/candy-tools/todo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todo"]
    end
  end

  # No zap stanza required
end
